//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.06 at 05:30:02 AM CET 
//


package com.siit.xml.modelCoverLetter;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuthorData" type="{http://localhost:8080/CoverLetter}AuthorData" maxOccurs="unbounded"/>
 *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="paperId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="paperTitle" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="commitDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="manuscriptTitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authorData",
    "content"
})
@XmlRootElement(name = "CoverLetter")
public class CoverLetter {

    @XmlElement(name = "AuthorData", required = true)
    protected List<AuthorData> authorData;
    @XmlElement(name = "Content", required = true)
    protected String content;
    @XmlAttribute(name = "paperId", required = true)
    protected String paperId;
    @XmlAttribute(name = "paperTitle", required = true)
    protected String paperTitle;
    @XmlAttribute(name = "commitDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar commitDate;
    @XmlAttribute(name = "manuscriptTitle")
    protected String manuscriptTitle;

    /**
     * Gets the value of the authorData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorData }
     * 
     * 
     */
    public List<AuthorData> getAuthorData() {
        if (authorData == null) {
            authorData = new ArrayList<AuthorData>();
        }
        return this.authorData;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the paperId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * Sets the value of the paperId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperId(String value) {
        this.paperId = value;
    }

    /**
     * Gets the value of the paperTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperTitle() {
        return paperTitle;
    }

    /**
     * Sets the value of the paperTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperTitle(String value) {
        this.paperTitle = value;
    }

    /**
     * Gets the value of the commitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCommitDate() {
        return commitDate;
    }

    /**
     * Sets the value of the commitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCommitDate(XMLGregorianCalendar value) {
        this.commitDate = value;
    }

    /**
     * Gets the value of the manuscriptTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManuscriptTitle() {
        return manuscriptTitle;
    }

    /**
     * Sets the value of the manuscriptTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManuscriptTitle(String value) {
        this.manuscriptTitle = value;
    }

}
