//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:26:53 PM CET 
//


package com.siit.xml.model.publication;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.siit.xml.utils.rdf.RDFID;
import com.siit.xml.utils.rdf.RDFSerializable;


/**
 * <p>Java class for TReviewer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TReviewer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reviewerUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TReviewer", propOrder = {
    "reviewerUsername"
})
@RDFSerializable(TypeUri = "user")
public class TReviewer {

    @XmlElement(required = true)
    @RDFID
    protected String reviewerUsername;

    /**
     * Gets the value of the reviewerUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewerUsername() {
        return reviewerUsername;
    }

    /**
     * Sets the value of the reviewerUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewerUsername(String value) {
        this.reviewerUsername = value;
    }

}
