//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.24 at 06:31:46 PM CEST 
//


package com.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SciencePaper_QNAME = new QName("http://foo.bar", "SciencePaper");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TBasicInformation }
     * 
     */
    public TBasicInformation createTBasicInformation() {
        return new TBasicInformation();
    }

    /**
     * Create an instance of {@link TParagraph }
     * 
     */
    public TParagraph createTParagraph() {
        return new TParagraph();
    }

    /**
     * Create an instance of {@link TPublication }
     * 
     */
    public TPublication createTPublication() {
        return new TPublication();
    }

    /**
     * Create an instance of {@link TReference }
     * 
     */
    public TReference createTReference() {
        return new TReference();
    }

    /**
     * Create an instance of {@link TAuthor }
     * 
     */
    public TAuthor createTAuthor() {
        return new TAuthor();
    }

    /**
     * Create an instance of {@link TReviewer }
     * 
     */
    public TReviewer createTReviewer() {
        return new TReviewer();
    }

    /**
     * Create an instance of {@link TCitation }
     * 
     */
    public TCitation createTCitation() {
        return new TCitation();
    }

    /**
     * Create an instance of {@link TBasicInformation.Title }
     * 
     */
    public TBasicInformation.Title createTBasicInformationTitle() {
        return new TBasicInformation.Title();
    }

    /**
     * Create an instance of {@link TParagraph.Element }
     * 
     */
    public TParagraph.Element createTParagraphElement() {
        return new TParagraph.Element();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPublication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://foo.bar", name = "SciencePaper")
    public JAXBElement<TPublication> createSciencePaper(TPublication value) {
        return new JAXBElement<TPublication>(_SciencePaper_QNAME, TPublication.class, null, value);
    }

}
