//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.24 at 06:31:46 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://foo.bar", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xml;
