//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.03 at 09:45:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/User", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.siit.xml.modelUser;
